### ISSUE TITLE
Depends on cloud?

### ISSUE THREAD

**Issue by adepiero** [InTheDaylight14/nginx-proxy-manager-switches#5]
Hello.
I do not understand why the integration appears on HA with the "depends on the cloud" icon.
Please, can you explain it?
Thank you.

![immagine](https://github.com/InTheDaylight14/nginx-proxy-manager-switches/assets/58445647/e67aaa85-6034-4ab3-823c-e9711a14298f)

**Comment by InTheDaylight14** [comment]
It does not. Thanks for catching that. Updated with v1.0.2

**Comment by adepiero** [comment]
You're welcome. Thanks for fixing it! :-)

Il giorno lun 23 ott 2023 alle ore 17:18 InTheDaylight14 <
***@***.***> ha scritto:
